//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleWorker.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.FullCalenderSoap")]
    public interface FullCalenderSoap {
        
        // CODEGEN: Generating message contract since element name EventListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EventList", ReplyAction="*")]
        SaleWorker.ServiceReference1.EventListResponse EventList(SaleWorker.ServiceReference1.EventListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EventListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EventList", Namespace="http://tempuri.org/", Order=0)]
        public SaleWorker.ServiceReference1.EventListRequestBody Body;
        
        public EventListRequest() {
        }
        
        public EventListRequest(SaleWorker.ServiceReference1.EventListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EventListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double startDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double endDate;
        
        public EventListRequestBody() {
        }
        
        public EventListRequestBody(double startDate, double endDate) {
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EventListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EventListResponse", Namespace="http://tempuri.org/", Order=0)]
        public SaleWorker.ServiceReference1.EventListResponseBody Body;
        
        public EventListResponse() {
        }
        
        public EventListResponse(SaleWorker.ServiceReference1.EventListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EventListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EventListResult;
        
        public EventListResponseBody() {
        }
        
        public EventListResponseBody(string EventListResult) {
            this.EventListResult = EventListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FullCalenderSoapChannel : SaleWorker.ServiceReference1.FullCalenderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FullCalenderSoapClient : System.ServiceModel.ClientBase<SaleWorker.ServiceReference1.FullCalenderSoap>, SaleWorker.ServiceReference1.FullCalenderSoap {
        
        public FullCalenderSoapClient() {
        }
        
        public FullCalenderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FullCalenderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FullCalenderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FullCalenderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SaleWorker.ServiceReference1.EventListResponse SaleWorker.ServiceReference1.FullCalenderSoap.EventList(SaleWorker.ServiceReference1.EventListRequest request) {
            return base.Channel.EventList(request);
        }
        
        public string EventList(double startDate, double endDate) {
            SaleWorker.ServiceReference1.EventListRequest inValue = new SaleWorker.ServiceReference1.EventListRequest();
            inValue.Body = new SaleWorker.ServiceReference1.EventListRequestBody();
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            SaleWorker.ServiceReference1.EventListResponse retVal = ((SaleWorker.ServiceReference1.FullCalenderSoap)(this)).EventList(inValue);
            return retVal.Body.EventListResult;
        }
    }
}
